### ISSUE TITLE
前端页面启动错误

### ISSUE THREAD

**Issue by 8824PPZ** [969025903/ChopperBot#38]
![image](https://github.com/969025903/ChopperBot/assets/36729296/2b6680b3-4736-443c-8b90-c52797234587)

**Comment by 969025903** [comment]
前端的所有依赖都导入了吗

**Comment by 8824PPZ** [comment]
导了

**Comment by 8824PPZ** [comment]
我不太懂前端的编译 ,直接敲的 npm install ，然后npm run dev

**Comment by Klein422** [comment]
有没有运行npm install 后的截图
如：
![image](https://github.com/969025903/ChopperBot/assets/96029217/1e7b09f4-68a0-4f07-a2ca-e1750f7350f0)

**Comment by 8824PPZ** [comment]
![微信截图_20231018175304](https://github.com/969025903/ChopperBot/assets/36729296/65c33caf-6a31-4e17-8af8-902bc67d226b)

**Comment by 8824PPZ** [comment]
> 暂时没有复现出您的bug，如果你需要使用前端，可以在console-ui下执行vite build 命令 然后将console-ui生成的dist文件夹中的内容复制到chopperbot-console模块下的/resources/static/ 如下图所示： ![image](https://user-images.githubusercontent.com/77137063/276196174-d347fdc8-d0ad-445d-ad90-967fafc68a79.png) 然后启动chopperbot-console即可

![image](https://github.com/969025903/ChopperBot/assets/36729296/d683fc07-25bf-4178-a89b-78564b3a1fd2)

**Comment by 969025903** [comment]
`npm install -g sass` 你可以尝试一下这个命令，如果还是不行
麻烦提供一下 您当前node的版本

**Comment by 8824PPZ** [comment]
> `npm install -g sass` 你可以尝试一下这个命令，如果还是不行 麻烦提供一下 您当前node的版本

![image](https://github.com/969025903/ChopperBot/assets/36729296/612a1326-58ff-4bce-903b-34209c3a57e2)
都是用的最新版本

**Comment by 8824PPZ** [comment]
原来node21 和Dart有兼容性问题。
https://github.com/dart-lang/sdk/issues/53784
